---
output: rmarkdown::github_document

---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE,
                      collapse = TRUE)



library(companycolors)
library(ggplot2)
theme_set(theme_minimal())
```


**`companycolors`** is an R helper package for using company-specific color palettes in charts.

### Usage

#### Pull list of company colors and HEX codes

```{r}
measure_colors()
```

#### Find HEX code from specific color
```{r}
measure_colors("Navy")
```

#### Get shades between two colors
```{r}
measure_palette("secondary", reverse = TRUE)(4)
```


#### Preview your color palettes
```{r, fig.width= 5, fig.height= 3}
glimpse_colors(measure_palette("mixed")(25))
glimpse_colors(measure_palette("accent", reverse = TRUE)(15))
```



#### Plot!

```{r, fig.width=6, fig.height=4}
ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Sepal.Length)) +
    geom_point(size = 4, alpha = 0.6) +
    scale_color_measure(discrete = FALSE, palette = "mixed", reverse = TRUE)
```


```{r, fig.width=6, fig.height=4}
ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) +
   geom_point(size = 4) +
   scale_color_measure(palette = "primary", reverse = FALSE)
 
```




### Credits
Based on this great @drsimonj [blog post](https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2)


